# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pr: none

pool:
  vmImage: 'macos-12'

steps:
  - checkout: self
    submodules: true
    
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '$(CERTFILENAME)'
      certPwd: '$(CERTP12PASSWORD)'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(APPTARGETPROVISIONFILENAME)'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(WIDGETTARGETPROVISIONFILENAME)'
  
  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(WATCHTARGETPROVISIONFILENAME)'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(WATCHEXTTARGETPROVISIONFILENAME)'
  - task: ios-bundle-version@1
    inputs:
      sourcePath: '/Users/runner/work/1/s/HolyQuran/Support/Info.plist'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildId)'
      versionName: 
      printFile: true

  - task: CocoaPods@0
    displayName: 'Install dependencies'

  - task: Xcode@5
    inputs:
      actions: 'archive'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_14.0.1.app'
      configuration: 'Release'
      xcWorkspacePath: 'HolyQuran.xcworkspace'
      scheme: 'HolyQuran'
      signingOption: 'default'
      sdk:
      packageApp: true
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
      exportArgs: '--dsym=true'
      exportOptions: 'plist'
      exportOptionsPlist: 'ExportOptionsCI.plist'
      useXcpretty: true
  - task: CopyFiles@2
    inputs:
      Contents: |
        **/*.ipa
        **/*.dSYM/**
      TargetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'ipa-files'
      artifactType: 'container'
  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'Holy-Quran-Test'
      appSlug: '$(APP_SLUG)'
      appFile: '$(Build.ArtifactStagingDirectory)/**/*.ipa'
      symbolsDsymFiles: '$(Build.ArtifactStagingDirectory)/**/dSYMs'
      releaseNotesOption: 'file'
      releaseNotesFile: 'CHANGELOG'
      destinationType: 'groups'
      distributionGroupId: '$(DISTRIBUTION_GROUP_ID)'
